dist: xenial
language: go

services:
  - docker

go:
  - 1.13.x
  # - TODO master

# skip non-trunk PMM-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{4}/

go_import_path: github.com/percona/mongodb_exporter

matrix:
  allow_failures:
    - go: master

stages:
  - build
  - test
  - deploy

env:
  global:
    - TMPDIR=/tmp
  matrix:
    # https://www.mongodb.com/support-policy
    - MONGODB_IMAGE=mongo:3.4
    - MONGODB_IMAGE=mongo:3.6
    - MONGODB_IMAGE=mongo:4.0

    # https://www.percona.com/services/policies/percona-software-platform-lifecycle#mongodb
    - MONGODB_IMAGE=percona/percona-server-mongodb:3.4
    - MONGODB_IMAGE=percona/percona-server-mongodb:3.6
    - MONGODB_IMAGE=percona/percona-server-mongodb:4.0

script: make test-all

jobs:
  include:
    - stage: build
      script:
        - make check-vendor-synced style build

    - stage: deploy
      script: skip
      deploy:
        provider: script
        script: make community-release
        on:
          tags: true

after_success:
  - curl https://codecov.io/bash > codecov
  - chmod +x codecov
  - timeout --signal=KILL 10s ./codecov -X fix

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: updWrOALfF29z30ogJ4m21WX0oOSYbRX/+abuEqXCC9zZ2QI7EoRR61hrAgNXJXUTffmUIM0vCrToYlybMsdcZHwCXWN8vr2yW3fyypfs/+rUng1qigEy1wVVIFgAC/6NruhmuUMWo1qwe4tUenQmegBiSpYRVRI10Qsnj6TggCNVz0cuoxpmzpVvNH78s1elnU4P1REWhjStuqQvKgG5cWOsvI+9l2Z+t9HdpYE7E7N3Ec73t2Z4wKhlpScbLF+mhnTWV6zgCkLaVdMshFeBEuYWmRr3D2QJWMntl/DrVaRoW76kX9nm2PQ/P4q0BdQslf5WsAiONWPOOWqK6n9RM9SegGSEXnXiqkWtmJQspa3zhjkNZStaD/g5E4yP5QnTbk4WP8ma18yQfMthXeQiQOEWj6zOTzBslu6Iyyc9QzbNijnYy3ZBBBAWGaKjFKmTrMTgl19SbAsvgi41A+zrVL5LeCwAR0/2QUdMegHZSla9WBiURgT/quA8EnA3N+ObNQBpqBETJmSPpJbqrkZI8+7oo4nFxLkwCRVyI4/XInTl5aKsRNYP95kPX3zJuUEe8x39qYhG5QcGV8G8AK0B+jrGoEB2qSN2p+Ye1XE6+Z38KktVzM3GmMOt/v+ts1ZjiaZvK0zlb7vRTMuiBmAjAnB5l5vmNSjkP6+ZL832Og=
  email: false
