name: goreleaser

on:
  push:
    # run when new tag is pushed
    tags:
      - v*
  # manually trigger the release
  workflow_dispatch:
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses:  percona-platform/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: percona-platform/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Login to Docker Hub
        uses: percona-platform/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Login to GitHub Container Registry
        uses: percona-platform/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Run GoReleaser
        uses: percona-platform/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
