name: goreleaser

on:
  push:
    # run when new tag is pushed
    tags:
      - v2.*
  # manually trigger the release
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        default: 'main'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses:  percona-platform/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: percona-platform/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Run GoReleaser
        uses: percona-platform/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}